project_id = "kubocyhvejzgsisihhrt"
api_url = "https://kubocyhvejzgsisihhrt.supabase.co"
api_anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Ym9jeWh2ZWp6Z3Npc2loaHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzc4ODMsImV4cCI6MjA2MTc1Mzg4M30.fuvRFzX9ju0rmcJ-ZiVKbGedL8-xPXEWxcPK5VShpiE" 